tag: "regression"
model_name: 'FeatureExtractorCNN'
data:
  transform: [swap_channels]
  target_transform: [swap_channels]
  bucketize: False
  load_raw_coords: True
  batch_size: 1
device: 'cuda'
loss_fn: 'ScaledMAE'
training:
  lr: 1.e-4
  lr_min: 1.e-6
  num_epochs: 200
  weight_decay: 1.0e-6
model:
  hidden_dims: [256,256,256,256]
  norm: null
  activation: relu
  conv_type: standard
  proj_dim: 256
  projection: mlp
  mlp_norm: null

